- name: configure reaper database server
  hosts: reapertest
  sudo: True
  vars:
  tasks:
  - name: add mongodb repository
    apt_repository:
      repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
      state: present
  - name: ensure that apt cache is up to date
    apt: update_cache=yes
  - name: install packages
    apt: name={{item}} force=yes
    with_items:
      - wget
      - vim
      - htop
      - mongodb-org
    notify:
    - start mongodb
  - name: mongod.conf
    copy: src=mongod.conf dest=/etc/mongod.conf
  - name: mongodb service
    copy: src=mongodb.service dest=/etc/systemd/system/mongodb.service
  handlers:
    - name: start mongodb
      sudo: yes
      command: systemctl start mongodb
