- name: configure reaper database server
  hosts: reapertest
  sudo: True
  vars:
  tasks:
  - name: add mongodb repository
    apt_repository:
      repo: 'deb http://archive.canonical.com/ubuntu hardy partner'
      state: present
  - name: ensure that apt cache is up to date
    apt: update_cache=yes
  - name: install packages
    apt: name={{item}} force=yes
    with_items:
      - wget
      - vim
      - htop
      - mongodb-org
  #handlers:
  #- name: restart varnish
  #  service: name=varnish state=restarted
